#pragma once

enum DIR { DIR_LEFT, DIR_RIGHT, DIR_UP, DIR_DOWN, DIR_END };

//PLAYER 기준으로 나중에 선언된 OBJ는 PLAYER 위에 그려짐
enum SYSID { SYS_MOUSE, SYS_END };
enum OBJID { OBJ_MOUSE, OBJ_PLAYER, OBJ_END
};
//오브젝트 추가를 위한 ID
enum SKILLID {
	SKILL_DASH,
	SKILL_ICE_SHIELD,
	SKILL_FDRAGON, SKILL_ICE_BLAST_MISSILE, SKILL_ICE_BLAST, SKILL_GAIA_ARMOR, WIZARD_FIRE, SOIL_SKILL, SOIL_COLUMN, SOIL_STON , SKILL_COMBO ,SKILLID_END
};
enum MONSTERID {
	SWORDMAN, SOWRDMAN_ATTCK, ACHERMAN, WIZARD, WIZARD_BALL, MIDDLE_BOSS, BOSS, MONSTER_END
};
enum UIID {
	UI_TELEPORT ,EFFECT_BOTTOM_HOLE, UI_MIDDLE_BOSS_BAR, UI_BOSS_BAR, UI_ITEM, UI_FONT, UI_GOLD,UI_SHOP, UI_PLAYER_BAR, UI_PLAYER_SKILL_BAR, UI_SKILL_BAR_ICON,UI_PLAYER_INVEN, UI_END
};

enum EFFECTID {
	FIRE_PARTICLE, SUMMON, EFFECT_HIT, EFFECT_SOIL, EFFECT_END
};
enum MENUID { MENU_BUTTON, MENU_END };
enum SCENEID { SCENE_LOGO = 0, SCENE_MENU = 1, SCENE_EDIT = 3, SCENE_STAGE = 2, SCENE_STAGE2 = 4, SCEN_ENDING = 5, SCENE_END = 6 };
enum TILE_OPT {
	TILE_OPT_MINIMAP,TILE_OPT_IRON,TILE_OPT_MONSTER_1, TILE_OPT_MONSTER_2, TILE_OPT_MONSTER_3,TILE_OPT_MONSTER_4 , TILE_OPT_MONSTER_5 ,
	TILE_OPT_MONSTER_6 , TILE_OPT_MONSTER_7 , TILE_OPT_MONSTER_8, TILE_OPT_MONSTER_9 , TILE_OPT_MONSTER_10,
	TILE_OPT_END };
enum PRO_SKILL { PRO_SKILL_DASH, PRO_SKILL_RUN, PRO_SKILL_ISHIELD, PRO_SKILL_FDRAGON, PRO_SKILL_ICE_BLAST, PRO_SKILL_GAIA_ARMOR, PRO_SKILL_END };
enum INVENTORY { INVEN_VKL, INVEN_SPACE, INVEN_Q, INVEN_E, INVEN_VKR, INVEN_R, INVEN_END };

enum RENDERID { BACKGROUND, GAMEOBJECT, EFFECT, RENDER_SKILL, UI, RENDER_END };

enum STATE_INVEN { SHOW, HIDE, STATE_INVEN_END };
enum SKILL { SKILL_WIND, SKILL_RUN, SKILL_CREATE, SKILL_CREATE_PUNCH, SKILL_LDASH, SKILL_RDASH, SKILL_END };
enum CHANNELID {SOUND_MAP, SOUND_BGM, SOUND_PLAYER_BACK ,SOUND_EFFECT,
	SOUND_BALL, SOUND_BALL_BACK,
	SOUND_MIDDLEBOSS,
	SOUND_BOSS, SOUND_BOSS_BACK,
	SOUND_ISHIELD,SOUND_ICEBLAST, SOUND_EFFECT_BACK,
	SOUND_GAIA_ARMOR,
	SOUND_SWORDMAN, SOUND_SWORDMAN_BACK,
	SOUND_ACHERMAN, SOUND_ACHERMAN_BACK,
	SOUND_PLAYER, SOUND_DASH, SOUND_FDRAGONE,
	SOUND_UI, MAXCHANNEL };